[app]
debug = true
addr = ":9421"
allow_cross_domain = true

[log]
filename = "log/data-view.log"
man_size = 256

[mysql]
address = "localhost"
port = "3306"
name = "data-view"
username = "root"
password = "root"

[storage]
type = "fastdfs"
# type = "minio"
# type = "custom"
url = "http://192.168.50.158:9000"